class human :
   def info(self):
        print("hello world!")
h1 = h2 = h3 = human()
h1.name =input("Enter your name : ")
h1.age = int(input("Enter yor age : "))
h1.city =input("Enter your city : ")
print(h1.name)
print(h1.age)
print(h1.city)
h2.name =input("Enter your name : ")
h2.age = int(input("Enter yor age : "))
h2.city =input("Enter your city : ")
print(h2.name)
print(h2.age)
print(h2.city)
h3.name =input("Enter your name : ")
h3.age = int(input("Enter yor age : "))
h3.city =input("Enter your city : ")
print(h3.name)
print(h3.age)
print(h3.city)
        